using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HizenLabs.Bundler;

/// <summary>
/// Generates the per-plugin kit wiring file (<c>&lt;Plugin&gt;.Kit.g.cs</c>) from the presence of
/// the plugin's config/lang classes - the bridge is always the same, so authors never write it:
///   - a class deriving <c>BaseConfig</c> produces the <c>config</c> field and the
///     LoadConfig/LoadDefaultConfig/SaveConfig overrides;
///   - a class deriving <c>BaseLang</c> produces the <c>L</c> field and LoadDefaultMessages.
/// One config and one lang per plugin, enforced. An override the author wrote by hand anywhere in
/// the plugin's parts is skipped (the author wins). The output is a real file on disk so the IDE
/// treats it as ordinary source - no source-generator machinery in the IntelliSense loop.
/// Purely syntactic: no semantic model, no game references.
/// </summary>
public static class KitWire
{
    private const string ConfigBase = "BaseConfig";
    private const string LangBase = "BaseLang";

    /// <summary>
    /// Computes the wiring file content for one plugin folder, or null when the plugin has no
    /// config/lang classes (no file should exist). Throws <see cref="KitWireException"/> on
    /// convention violations (more than one config/lang class).
    /// </summary>
    public static string Generate(string pluginName, IEnumerable<(string Path, string Text)> sources)
    {
        var configTypes = new List<string>();
        var langTypes = new List<string>();
        var authoredOverrides = new HashSet<string>(StringComparer.Ordinal);
        string ns = null;

        foreach (var (path, text) in sources)
        {
            var root = CSharpSyntaxTree.ParseText(text, path: path).GetRoot();
            foreach (var decl in root.DescendantNodes().OfType<TypeDeclarationSyntax>())
            {
                if (decl.Identifier.Text == pluginName)
                {
                    ns ??= (decl.Ancestors().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault())?.Name.ToString();
                    foreach (var method in decl.Members.OfType<MethodDeclarationSyntax>())
                    {
                        if (method.Modifiers.Any(SyntaxKind.OverrideKeyword))
                            authoredOverrides.Add(method.Identifier.Text);
                    }
                    continue;
                }
                if (decl.Parent is TypeDeclarationSyntax)
                    continue; // nested helper types are not plugin-level config/lang
                if (HasBase(decl, ConfigBase))
                    configTypes.Add(decl.Identifier.Text);
                else if (HasBase(decl, LangBase))
                    langTypes.Add(decl.Identifier.Text);
            }
        }

        if (configTypes.Count > 1)
            throw new KitWireException($"{pluginName}: one config class per plugin - found {string.Join(", ", configTypes)}");
        if (langTypes.Count > 1)
            throw new KitWireException($"{pluginName}: one lang class per plugin - found {string.Join(", ", langTypes)}");

        var config = configTypes.Count == 1 ? configTypes[0] : null;
        var langType = langTypes.Count == 1 ? langTypes[0] : null;
        if (config is null && langType is null)
            return null;

        var sb = new System.Text.StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//     Generated by 'hizenbundle wire'. DO NOT EDIT - rewritten on every build.\n");
        sb.Append("//     This is the standard kit bridge, bootstrapped from the plugin's config/lang classes.\n");
        sb.Append("// </auto-generated>\n");
        if (config is not null)
            sb.Append("using HizenLabs.Shared.Config;\n");
        if (langType is not null)
            sb.Append("using HizenLabs.Shared.Lang;\n");
        sb.Append('\n');
        if (ns is not null)
            sb.Append($"namespace {ns};\n\n");
        sb.Append($"public partial class {pluginName}\n{{\n");

        if (config is not null)
            sb.Append($"    private static {config} config;\n");
        if (langType is not null)
            sb.Append($"    private static readonly {langType} L = new();\n");

        if (config is not null)
        {
            if (!authoredOverrides.Contains("LoadConfig"))
                sb.Append($"\n    protected override void LoadConfig()\n    {{\n        base.LoadConfig();\n        config = ConfigKit.Load<{config}>(this);\n    }}\n");
            if (!authoredOverrides.Contains("LoadDefaultConfig"))
                sb.Append($"\n    protected override void LoadDefaultConfig()\n    {{\n        base.LoadDefaultConfig();\n        config = ConfigKit.Default<{config}>(this);\n    }}\n");
            if (!authoredOverrides.Contains("SaveConfig"))
                sb.Append("\n    protected override void SaveConfig()\n    {\n        base.SaveConfig();\n        ConfigKit.Save(this, config);\n    }\n");
        }
        if (langType is not null && !authoredOverrides.Contains("LoadDefaultMessages"))
            sb.Append("\n    protected override void LoadDefaultMessages()\n    {\n        base.LoadDefaultMessages();\n        LangKit.Register(this, L);\n    }\n");

        sb.Append("}\n");
        return sb.ToString();
    }

    private static bool HasBase(TypeDeclarationSyntax decl, string baseName) =>
        decl.BaseList is not null && decl.BaseList.Types.Any(t =>
            (t.Type is IdentifierNameSyntax id && id.Identifier.Text == baseName) ||
            (t.Type is QualifiedNameSyntax q && q.Right.Identifier.Text == baseName));

    /// <summary>
    /// Wires one plugin folder on disk: writes/updates <c>&lt;Plugin&gt;.Kit.g.cs</c>, or deletes
    /// it when the plugin has no config/lang. Returns a status string for logging, or null when
    /// the folder is not a plugin folder (no &lt;DirName&gt;.cs entry). Only touches the file when
    /// the content actually changed, so builds stay incremental.
    /// </summary>
    public static string WireFolder(string folder, bool checkOnly = false)
    {
        var pluginName = Path.GetFileName(Path.TrimEndingDirectorySeparator(folder));
        var entry = Path.Combine(folder, pluginName + ".cs");
        if (!File.Exists(entry))
            return null;

        var generatedPath = Path.Combine(folder, pluginName + ".Kit.g.cs");
        var sources = Directory.EnumerateFiles(folder, "*.cs", SearchOption.TopDirectoryOnly)
            .Where(f => !f.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase))
            .Select(f => (f, File.ReadAllText(f)));

        var content = Generate(pluginName, sources);
        var existing = File.Exists(generatedPath) ? File.ReadAllText(generatedPath) : null;
        var normalizedExisting = existing?.Replace("\r\n", "\n");

        if (content is null)
        {
            if (existing is null)
                return $"{pluginName}: no config/lang, no wiring";
            if (checkOnly)
                throw new KitWireException($"{pluginName}: {Path.GetFileName(generatedPath)} is stale (should not exist)");
            File.Delete(generatedPath);
            return $"{pluginName}: removed stale {Path.GetFileName(generatedPath)}";
        }

        if (normalizedExisting == content)
            return $"{pluginName}: wiring up to date";
        if (checkOnly)
            throw new KitWireException($"{pluginName}: {Path.GetFileName(generatedPath)} is stale - run a build (or 'hizenbundle wire') and commit it");
        File.WriteAllText(generatedPath, content);
        return $"{pluginName}: wrote {Path.GetFileName(generatedPath)}";
    }
}

public sealed class KitWireException : Exception
{
    public KitWireException(string message) : base(message) { }
}
